INSERT INTO Menu.Tree (ParentId, Title, OrderBy) VALUES (NULL, 'Objects', 1)
INSERT INTO Menu.Tree (ParentId, Title, OrderBy) VALUES (1, 'Milky Way (Sagittarius A)', 2)
INSERT INTO Menu.Tree (ParentId, Title, OrderBy) VALUES (2, 'Solar System (Sun)', 3)
INSERT INTO Menu.Tree (ParentId, Title, OrderBy) VALUES (3, 'Planets', 4)
INSERT INTO Menu.Tree (ParentId, Title, OrderBy) VALUES (4, 'Mercury', 5)
INSERT INTO Menu.Tree (ParentId, Title, OrderBy) VALUES (4, 'Venus', 6)
INSERT INTO Menu.Tree (ParentId, Title, OrderBy) VALUES (4, 'Earth', 7)
INSERT INTO Menu.Tree (ParentId, Title, OrderBy) VALUES (7, 'Moon', 8)
INSERT INTO Menu.Tree (ParentId, Title, OrderBy) VALUES (4, 'Mars', 9)
INSERT INTO Menu.Tree (ParentId, Title, OrderBy) VALUES (9, 'Phobos', 10)
INSERT INTO Menu.Tree (ParentId, Title, OrderBy) VALUES (9, 'Deimos', 11)
INSERT INTO Menu.Tree (ParentId, Title, OrderBy) VALUES (4, 'Jupiter', 12)
INSERT INTO Menu.Tree (ParentId, Title, OrderBy) VALUES (12, 'Io', 13)
INSERT INTO Menu.Tree (ParentId, Title, OrderBy) VALUES (12, 'Europa', 14)
INSERT INTO Menu.Tree (ParentId, Title, OrderBy) VALUES (12, 'Ganymede', 15)
INSERT INTO Menu.Tree (ParentId, Title, OrderBy) VALUES (12, 'Callisto', 16)
INSERT INTO Menu.Tree (ParentId, Title, OrderBy) VALUES (4, 'Dwarf Planets', 17)
INSERT INTO Menu.Tree (ParentId, Title, OrderBy) VALUES (17, 'Pluto', 18)
INSERT INTO Menu.Tree (ParentId, Title, OrderBy) VALUES (18, 'Charon', 19)
INSERT INTO Menu.Tree (ParentId, Title, OrderBy) VALUES (18, 'Nix', 20)
INSERT INTO Menu.Tree (ParentId, Title, OrderBy) VALUES (18, 'Hydra', 21)
INSERT INTO Menu.Tree (ParentId, Title, OrderBy) VALUES (17, 'Ceres', 22)
INSERT INTO Menu.Tree (ParentId, Title, OrderBy) VALUES (17, 'Eris', 23)
INSERT INTO Menu.Tree (ParentId, Title, OrderBy) VALUES (17, 'Haumea', 24)
INSERT INTO Menu.Tree (ParentId, Title, OrderBy) VALUES (3, 'Asteroids', 25)
INSERT INTO Menu.Tree (ParentId, Title, OrderBy) VALUES (25, '10 Hygiea', 26)
INSERT INTO Menu.Tree (ParentId, Title, OrderBy) VALUES (25, '101955 Bennu', 27)
INSERT INTO Menu.Tree (ParentId, Title, OrderBy) VALUES (25, '107 Cammilla', 28)
INSERT INTO Menu.Tree (ParentId, Title, OrderBy) VALUES (3, 'Comets', 29)
INSERT INTO Menu.Tree (ParentId, Title, OrderBy) VALUES (29, 'C/1995 O1 (Hale-Bopp)', 30)
INSERT INTO Menu.Tree (ParentId, Title, OrderBy) VALUES (29, '19P/Borrelly', 31)
INSERT INTO Menu.Tree (ParentId, Title, OrderBy) VALUES (29, '1P/Halley', 32)
INSERT INTO Menu.Tree (ParentId, Title, OrderBy) VALUES (2, 'Alpha Centauri (A)', 33)
INSERT INTO Menu.Tree (ParentId, Title, OrderBy) VALUES (33, 'Alpha Centauri B', 34)
INSERT INTO Menu.Tree (ParentId, Title, OrderBy) VALUES (33, 'Proxima Centauri', 35)
INSERT INTO Menu.Tree (ParentId, Title, OrderBy) VALUES (35, 'Proxima b', 36)
INSERT INTO Menu.Tree (ParentId, Title, OrderBy) VALUES (35, 'Proxima c', 37)
INSERT INTO Menu.Tree (ParentId, Title, OrderBy) VALUES (33, '1SWASP J1407', 38)
INSERT INTO Menu.Tree (ParentId, Title, OrderBy) VALUES (38, '1SWASP J1407 b', 39)
INSERT INTO Menu.Tree (ParentId, Title, OrderBy) VALUES (1, 'Day/Night Cycle', 40)
INSERT INTO Menu.Tree (ParentId, Title, OrderBy) VALUES (1, 'Enhanced Textures', 41)
GO