USE [SFS]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[Menu].[Tree]') AND type in (N'U'))
ALTER TABLE [Menu].[Tree] DROP CONSTRAINT IF EXISTS [FK_Tree_Tree]
GO
DROP TABLE IF EXISTS [Menu].[Tree]
GO
DROP SCHEMA IF EXISTS [Menu]
GO
CREATE SCHEMA [Menu]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Menu].[Tree](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[ParentId] [int] NULL,
	[MenuType] [nvarchar](50) NOT NULL,
	[Title] [nvarchar](50) NOT NULL,
	[OrderBy] [int] NOT NULL,
 CONSTRAINT [PK_Tree] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [Menu].[Tree]  WITH CHECK ADD  CONSTRAINT [FK_Tree_Tree] FOREIGN KEY([ParentId])
REFERENCES [Menu].[Tree] ([Id])
GO
ALTER TABLE [Menu].[Tree] CHECK CONSTRAINT [FK_Tree_Tree]
GO